<a href="https://colab.research.google.com/github/HenriqueCrj/AulasPython/blob/master/Henrique_Aula_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Questão 1 a)
def create_matrix():
    matrix = {}
    for i in range(5):
        for j in range(5):
            matrix[(i,j)] = 0
    matrix[(0,3)] = 1
    matrix[(2,1)] = 2
    matrix[(4,3)] = 3
    return matrix

def print_matrix(matrix):
    for i in range(5):
        print("|",end="")
        for j in range(5):
            print(matrix.get((i,j)),end="")
        print("|\n")

matrix = create_matrix()
print_matrix(matrix)

|00010|

|00000|

|02000|

|00000|

|00030|



In [2]:
#Questão 1 b)
import numpy as np

np_matrix = np.zeros(shape=(5,5))
np_matrix[0,3] = 1
np_matrix[2,1] = 2
np_matrix[4,3] = 3
print(np_matrix)

[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0.]]


In [3]:
#Questão 2 a)

def frequency_table(string):
    """Calcula a tabela de frequências
    Args:
        string: texto
    Returns:
        dictionary: dicionário contendo a tabela de frequências
    """
    dictionary = {}
    for letter in string.replace(" ",""):
        dictionary[letter] = dictionary.get(letter,0) + 1
    return dictionary

table = frequency_table("paralelepipedo")
print(table)

{'p': 3, 'a': 2, 'r': 1, 'l': 2, 'e': 3, 'i': 1, 'd': 1, 'o': 1}


In [4]:
#Questão 2 b)
def order_table(table):
    """Ordena uma tabela de frequências
    Args:
        table: tabela de frequências
    Returns:
        ordered_list: lista com a tabela de frequências ordenada
    """
    ordered_list = []
    for (key,value) in table.items():
        ordered_list.append([key,value])
    ordered_list.sort()
    return ordered_list

print(order_table(table))

[['a', 2], ['d', 1], ['e', 3], ['i', 1], ['l', 2], ['o', 1], ['p', 3], ['r', 1]]


In [5]:
#Questão 3
def ordered_frequency_table(string):
    """Calcula a tabela de frequências ordenada
    Args:
        string: texto
    Returns:
        lista com a tabela de frequências ordenada
    """
    table = frequency_table(string.lower())
    return order_table(table)


alphabeticaly_ordered_list = ordered_frequency_table("ThiS is String with Upper and lower case Letters")
for letter in alphabeticaly_ordered_list:
    print(letter) 

['a', 2]
['c', 1]
['d', 1]
['e', 5]
['g', 1]
['h', 2]
['i', 4]
['l', 2]
['n', 2]
['o', 1]
['p', 2]
['r', 4]
['s', 5]
['t', 5]
['u', 1]
['w', 2]
